package com.javatpoint;

import org.springframework.stereotype.Component;
import java.util.List;
import java.util.stream.Collectors;

@Component
public class ProductMapper {

    // ENTITY → DTO
    public ProductDTO toDTO(Product product) {
        if (product == null) return null;

        ProductDTO dto = new ProductDTO();
        dto.setId(product.getId());
        dto.setName(product.getPname());
        dto.setBatch(product.getBatchno());
        dto.setPrice(product.getPrice());
        dto.setQuantity(product.getNoofproduct());

        return dto;
    }

    // DTO → ENTITY
    public Product toEntity(ProductDTO dto) {
        if (dto == null) return null;

        Product product = new Product();
        //product.setId(dto.getId());   since autogenerated
        product.setPname(dto.getName());
        product.setBatchno(dto.getBatch());
        product.setPrice(dto.getPrice());
        product.setNoofproduct(dto.getQuantity());

        return product;
    }

    // ENTITY LIST → DTO LIST
    public List<ProductDTO> toDTOList(List<Product> products) {
        return products.stream()
                .map(this::toDTO)
                .collect(Collectors.toList());
    }

    // DTO LIST → ENTITY LIST
    public List<Product> toEntityList(List<ProductDTO> products) {
        return products.stream()
                .map(this::toEntity)
                .collect(Collectors.toList());
    }
}
